apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3  # Number of desired pod replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-image:latest  # Docker image for the application
        ports:
        - containerPort: 8080  # Port exposed by the application

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Select pods with this label to route traffic
  ports:
  - protocol: TCP
    port: 80  # Service port
    targetPort: 8080  # Port on the pod to forward traffic to
  type: ClusterIP  # Service type (ClusterIP, NodePort, LoadBalancer)

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-app-route
spec:
  to:
    kind: Service
    name: my-app-service
  port:
    targetPort: 8080  # Port on the service to expose
  tls:
    termination: edge  # Termination type (edge, passthrough)
